steps: 
  - label: Upload
    key: step1
    command: buildkite-agent artifact upload "./upload.txt"
    env:
      BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "s3://priyak-test-bucket/$BUILDKITE_BUILD_NUMBER/"
      BUILDKITE_S3_ACL: "private"
      BUILDKITE_S3_ACCESS_URL: "https://priyak-test-bucket.s3.amazonaws.com/$BUILDKITE_BUILD_NUMBER/66/upload.txt"


