steps: 
  - label: Upload
    key: step1
    command: buildkite-agent artifact upload "./artifact.txt"
    env:
      BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "s3://priyak-test-bucket/$BUILDKITE_BUILD_NUMBER/"
