
steps: 

  
  - command: sleep 200

  - trigger: trigger
    key: trigger
    label: "Triggering pipelines"

  - wait: ~
  
  - label: "Run only if above pass"
    command: |
      if [ $$(buildkite-agent step get "outcome" --step "trigger") != "passed" ]; then
         cat <<- YAML | buildkite-agent pipeline upload 
         steps:
            - label: "Cancelling the build"
              cancel_on_build_failure: true
      YAML
      fi
  
    
  - label: Upload
    key: step1
    command: buildkite-agent artifact upload "./upload.txt"

  - label: Download
    depends_on: step1
    command: buildkite-agent artifact download "*upload.txt" .

