plugins: &plugins
  - seek-oss/github-merged-pr#v1.1.2:
      mode: checkout

steps:

  - label: 1st step
    command: echo "hello"
    plugins:
      <<: *plugins


  - label: 2st step
    command: echo "test"
    plugins:
      <<: *plugins


