
steps:

  
  - block: "unblock step one"
    key: "one"

  - label: ":step 1:"
    command: echo "hi"

  
  - block: "unblock step two"
    key: "two"

  - label: ":step 2:"
    command: echo "hi"

  
  - block: "unblock step three"
    key: "three"

  - label: ":step 3:"
    command: echo "hi"



