plugins: &plugins
  - seek-oss/github-merged-pr#v1.1.2:
      mode: checkout

steps:

  - label: 1st step
    command: echo "hello"
    plugins:
      <<: *plugins


  - label: 2st step
    key: 2
    command: echo "test"
    plugins:
      <<: *plugins

  
  
  - label: 3rd step
    depends_on:
    - 3
    command: echo "hi"
    plugins:
      <<: *plugins

