steps:
- label: Deploy to testing
  branches: master feature/*
- label: Deploy to staging
  branches: master release/* hotfix/*
- block: ":rocket: Release"
  branches: master
- label: Deploy to production
  branches: master
