
steps:

  - input: "Information please"
    key: "information"
    fields:
      - text: "What is the date today?"
        key: "todays-date"

  - label: ":rocket:"
    command: "hi"
    depends_on: "information"
  
  - block: "Release"
    blocked_state: "running"
    key: "release"

  - label: ":rocket:"
    command: "hi"
    depends_on: "release"


