---
steps:
- label: "TARGET_CLUSTER: ${TARGET_CLUSTER} and buildkite-agent meta-data get selected_cluster"
  key: cd
  command: echo "cds"

- label: ":label: contains invalid"
  command: echo "contains a label"
  if: "build.pull_request.labels =~ \"invalid\""

- label: ":label: no invalid"
  command: echo "no label"
  if:  "build.pull_request.labels !~ \"invalid\""

- command: echo "-> Start of concurrency gate"
  concurrency_group: gate
  concurrency: 1
  key: start-gate
  depends_on: "cd"

- wait:

- label: ":rocket: trigger  ci"
  command: echo "cd"
  key: cd-gate
  depends_on: start-gate

- label: ":rocket: trigger  cd"
  command: sleep 1
  parallelism: 1
  key: cd-trigger
  depends_on: "cd-gate"

- wait:

- label: ":rocket: trigger  ci end gate"
  command: echo "End of concurrency gate <--"
  concurrency_group: gate
  concurrency: 1
  key: end-gate

- command: echo "This and subsequent steps run independently"
  depends_on: "end-gate"
