- command:  echo "$concurrency_group_id"
  label: ':rocket: Deploy production'
  concurrency: 6
  concurrency_group: deploy

- command:  anoth one
  label: ':rocket: Deploy staging'
  concurrency: 6
  concurrency_group: deploy