- command:  echo "$concurrency_group_id"
  label: ':rocket: Deploy production'
  key: deploy_production
  concurrency: 6
  parallelism: 2
  concurrency_group: deploy
  env:
    concurrency_token: $BUILDKITE_PARALLEL_JOB-deploy_production

- command:  echo "anoth one"
  key: deploy_staging
  
  label: ':rocket: Deploy staging'
  concurrency: 6
  concurrency_group: deploy
  env:
    concurrency_token: $BUILDKITE_PARALLEL_JOB-$BUILDKITE_STEP_KEY