- command:  buildkite-agent step update "label" $BUILDKITE_PARALLEL_JOB-$BUILDKITE_STEP_KEY --append
  label: ':rocket: Deploy production'
  key: deploy_production
  concurrency: 6
  parallelism: 2
  concurrency_group: deploy
  env:
    concurrency_token: $BUILDKITE_PARALLEL_JOB-deploy_production

- command:  echo "anoth one"
  key: deploy_staging
  
  label: echo "$buildkite-agent meta-data get "available""
  concurrency: 6
  concurrency_group: deploy
  env:
    concurrency_token: $BUILDKITE_PARALLEL_JOB-$BUILDKITE_STEP_KEY