steps:
- label: "Script"
  key: step1
  command: echo "your script"
  notify:
    - github_commit_status:
        context: "my custom status"

- label: " notify?"
  command: |
    if [ $$(buildkite-agent step get "outcome" --step "step1") != "passed" ]; then
        cat <<- YAML | buildkite-agent pipeline upload 
        steps:
          - label: "Notify slack about soft passed step"
            notify:
              - github_commit_status:
                  context: "my custom status"
      YAML
      fi
