
steps:
  - label: ":docker: Build once, push to multiple ECR"
    plugins:
      - ecr#v2.3.0:
          credential-helper: true
          account-ids:
            - "097340723131"
            - "public.ecr.aws"
    commands: ./src/push_image_ecr.sh
