
steps:
  - label: ":docker: Build once, push to multiple ECRs"
    plugins:
      - ecr#v2.3.0:
          login: true
          account_ids: "097340723131"
          region: "us-east-1"
          extra_build_args:
            - "--pull"
          skip_push: true 
      - aws-assume-role-with-web-identity#v1.4.0:
          role-arn: arn:aws:iam::767828730660:role/priya-cross-account-role
    commands: ./src/push_image_ecr.sh
