
steps:
  - label: ":docker: Build once, push to multiple ECRs"
    plugins:
      - ecr#v2.3.0:
          login: true
          account_ids: "097340723131"
          region: "us-east-1"
          extra_build_args:
            - "--pull"
          skip_push: true 
    commands: ./src/push_image_ecr.sh
     
