---
steps:

- label: "test webhook"
  command: |
    WEBHOOK="$(buildkite-agent meta-data get buildkite:webhook)"
    echo "The current repository has $WEBHOOK  💫"

- label: "setup"
  key: setup
  command: echo "./src/setup.sh"