---
steps:

- label: "test webhooks"
  command: |
    WEBHOOK="$(buildkite-agent meta-data get buildkite:webhook)"
    echo "The current repository has $WEBHOOK  💫"
    echo `buildkite-agent meta-data get buildkite:webhook`

- label: "setup"
  key: setup
  command: echo "./src/setup.sh"