steps:
  - label: "Triggering pipelines"
    plugins:
      - monorepo-diff#v1.4.0:
          watch:
            - path: ".buildkite/"
              config:
                trigger: "child-pipeline"
                label: "Triggered deploy"
                build:
                  message: "Deploying foo service"
                  env:
                    - tool=Axe
