steps:
  - label: "Triggering pipelines"
    plugins:
      - monorepo-diff#v1.5.1:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: src/
              config:
                command: "src/generate.sh | buildkite-agent pipeline upload"