steps:
  - label: "Triggering pipelines"
    key: "monorepo-trigger"
    plugins:
      - monorepo-diff#v1.5.1:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: src/
              config:
                command: exit 0



  - label: "Run for any changes within src/"
    command: echo "Changes detected in src/, running pipeline..."
    if_changed: src/**