steps:
  - label: "Triggering pipelines"
    plugins:
      - monorepo-diff#v1.5.0:
          diff: "git diff --name-only HEAD~1"
          watch:
            - path: app/
              config:
                trigger: "artifact-s3"