steps:
  - input: "Cluster to deploy"
    key: "cluster_select"
    fields:
    - select: "Cluster"
      key: "selected_cluster"
      required: true
      default: "main"
      options:
        - label: "cluster"
          value: "staging"
  - label: "Trigger pipelines based on changes to specific paths"
    depends_on: "cluster_select"
    if: build.branch == "main"
    plugins:
      - ssh://git@github.com/PriyaSudip/monorepo-diff-buildkite-plugin.git:
          watch:
            # Trigger for grok-in-xai-build-and-deploy
            - path:
                - .buildkite/
              config:
                trigger: "child-pipeline"
                build:
                  meta_data:
                    selected_cluster: "buildkite-agent meta-data get selected_cluster"
                  env:
                    target_cluster: "${TARGET_CLUSTER:-buildkite-agent meta-data get selected_cluster}"
                    
