steps:
- label: ":test multi line:"
  command: echo  "hello" | buildkite-agent artifact upload "*.txt"
  key: test1


- label: ":test multi line:"
  command: echo "$(buildkite-agent artifact search "*.txt" --step test1)" | buildkite-agent artifact download "*.txt" --step test1
  depends_on: test1
