steps:
  - label: "test"
    skip: false
    command: echo "test"
    env:
      SERVER: """
  
  - label: "build"
    branches: test
    command: echo "build"
  
  - label: "deploy"
    command: echo "decploy"