---
steps:

- key: dd_key_test_one
  label: step_1
  retry:
    automatic:
      limit: 2
  command: echo "hi from webhook"| exit 1
  key: one
  env:
    $TEST_ENV_CMD: "True"
  notify:
    - if: "build.branch == \"main\" && build.state != 'failing' && build.state != 'failed' && build.state != 'canceling' && build.state != 'canceled'"
      slack:
        message: ":large_green_circle: [data] Production Deploy Starting"
        channels:
        - "#data-test"
- key: dd_key_test_two
  depends_on: 
  label: step_2
  command: buildkite-agent meta-data set "dd_tags.retry_type" $BUILDKITE_RETRY_TYPE | buildkite-agent meta-data set "dd_tags.retry" ${BUILDKITE_RETRY_COUNT}
- key: dd_key_test_three
  label: step_3
  command: buildkite-agent meta-data set "dd_tags.key" dd_key_test_three