steps:
  - label: "test"
    skip: false
    command: exit -1
    env:
      SERVER: ""
  
  - label: "build"
    branches: test
    command: echo "buildcc gh"
  
  - label: "deploy"
    command: echo "decploy"