---
steps:
- key: dd_key_test_one
  label: test
  command: echo "dd_key_test_one" | buildkite-agent meta-data set "dd_tags.key" dd_key_test_one
- key: key_two
  label: test1
  command: echo "$BUILDKITE_PIPELINE_SLUG" | buildkite-agent meta-data set "dd_tags.pipeline" $BUILDKITE_PIPELINE_SLUG