---
steps:
env:
  BUILDKITE_AGENT_DEBUG_SIGNING:True
- key: dd_key_test_one
  label: step_1
  command: exit 1
  env:
    $TEST_ENV_CMD: "True"
  soft_fail:
    - exit_status: 1
- key: dd_key_test_two
  label: step_2
  command: buildkite-agent meta-data set "dd_tags.key" dd_key_test_two
- key: dd_key_test_three
  label: step_3
  command: buildkite-agent meta-data set "dd_tags.key" dd_key_test_three