---
steps:
- key: dd_key_test_one
  label: step_1
  command: buildkite-agent meta-data set "dd_tags.key" dd_key_test_one
- key: dd_key_test_two
  label: step_2
  command: buildkite-agent meta-data set "dd_tags.key" dd_key_test_two