steps:
  - label: check if commit should be skipped
    key: skip-commit
    plugins:
      - git@github.com:PriyaSudip/skip-commit-build-buildkite-plugin.git

  - label: ":eslint: Lint: TS (v3)"
    depends_on: skip-commit
    command: echo "hello"
