steps:
  - command: ./src/validation.sh | echo "Validation step completed.$$SLACK_MESSAGE"
    notify:
      - slack:
          channels: ["#priya-test"]
          message: buildkite-agent meta-data get slack_message

