steps:
  - command: git sparse-checkout init | git sparse-checkout set .buildkite | git checkout main | buildkite-agent meta-data set 'buildkite:git:commit' "$$BUILDKITE_COMMIT" 
    key: 'step1'

  - command: buildkite-agent meta-data set 'buildkite:git:commit' "5674"
    depends_on: step1
    key: 'step2'