---
steps:
  - command: echo "Upload artifact"
    key: ci
    command: buildkite-agent artifact upload "artifact.txt

  - label: ":rocket: trigger  cd"
    trigger: child1
    key: cd-trigger
    depends_on: "ci"
