---
steps:
- label: Testing triggers
  command: echo "hello"
- build:
    meta_data:
      release-version: '1.1'
  label: ":rocket: Deploy event trigger"
  trigger: step-notification
  branches: main