#!/bin/bash
set -euo pipefail

if [[ "${BUILDKITE_BRANCH}" =~ ^ain/(.*) ]]; then
	export BUILDKITE_BRANCH_SLUGIFIED="merge-queue"
fi

export BUILDKITE_BRANCH_SLUGIFIED="merge-queue"
echo "BUILDKITE_BRANCH_SLUGIFIED from pre command $BUILDKITE_BRANCH_SLUGIFIED"

echo "BUILDKITE_BRANCH_SLUGIFIED $BUILDKITE_BRANCH_SLUGIFIED"
echo "pre-exit hook, running"


pwd
ls



cd src

ls






echo "script called"